### ISSUE TITLE
Split location controller into staged and published location

### ISSUE THREAD

**Issue by cellador** [cellador/vivid-streets#18]
- Users can create entities that will be stored in a "staged location" collection
- Admins can publish "staged locations", moving them into the "published location" collection
- Admins can edit all locations
- All visitors can GET all "published locations"

Related issue: #14

**Comment by jphorak** [comment]
working on this currently

**Comment by jphorak** [comment]
basically done with this. need authentication via jwt in backend for posting public locations etc now

**Comment by cellador** [comment]
I'd consider this done with 8efbeac820fd7796a38afc578fe141d2f64c1eff, thank you @jphorak!
